spring:
  application:
    name: Gerenciador-de-reservas
  datasource:
    url: jdbc:h2:mem:reserve
    username: sa
    password: admin123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
